### ISSUE TITLE
Credentials in the settings and account number from paybill

### ISSUE THREAD

**Issue by kimutaiRop** [lemaiyan/mpesa_api#7]
Hello I believe this is really helpful but I have some issues that is, the credentials you listed in the settings are so many yet in the developer I think I got almost 7 and with reaaly different names. I wanted to ask if you can give commented code of what in the developer site  each of those variables really points to, That will be really helpful.
again how do I get the account number for a C2B trasaction from the json data. thankyou

**Comment by lemaiyan** [comment]
Hey @kimutaiRop  the Account number is labeled as `BillRefNumber`. As for the settings, they include setting also for `B2C` if you only interested with Paybill( C2B) just update those. All the same, I will add comments and group them

**Comment by kimutaiRop** [comment]
thanks @lemaiyan they really helped. my app is now up and running using this... only one issue though. which task should I use to update custom database models.
